##.title
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##
## Copyright © dev-cetera.com & contributors.
##
## The use of this source code is governed by an MIT-style license described in
## the LICENSE file located in this project's root directory.
##
## See: https://opensource.org/license/mit
##
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##.title~

name: gen_translations_gemeni
homepage: https://dev-cetera.com/
repository: https://github.com/robmllze/df_localization
funding:
- https://www.buymeacoffee.com/dev_cetera
- https://www.patreon.com/c/RobertMollentze
- https://github.com/sponsors/robmllze

## -----------------------------------------------------------------------------

environment:
  sdk: ">=3.5.0 <4.0.0"

## -----------------------------------------------------------------------------

dependencies:
  path: ^1.9.1
  args: ^2.7.0
  yaml: ^3.1.3
  df_log: ^0.3.20
  google_generative_ai: ^0.4.7

## -----------------------------------------------------------------------------

dev_dependencies:
  df_localization:
    path: ../
  lints: ^6.0.0

