name: example
publish_to: 'none'
environment:
  sdk: ^3.7.0
dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http:
  cupertino_icons: ^1.0.8
  df_config:
    path: ../../df_config
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true