name: example
publish_to: 'none'
environment:
  sdk: ^3.7.0
dependencies:
  flutter:
    sdk: flutter
  df_pod:
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http:
  df_localization:
    path: ../
  df_config:
    path: ../../df_config
  df_safer_dart:
dev_dependencies:
  flutter_lints: ^5.0.0