name: df_localization_example
homepage: https://dev-cetera.com/
funding:
- https://www.buymeacoffee.com/dev_cetera
- https://www.patreon.com/c/robelator
- https://github.com/sponsors/robelator
- https://www.patreon.com/c/robelator
- https://github.com/sponsors/robelator
- https://www.buymeacoffee.com/dev_cetera


publish_to: 'none'
environment:
  sdk: ">=3.5.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  df_localization:
    path: ../
  df_config: ^0.8.0
  df_safer_dart: ^0.21.0
  df_pod: ^0.20.0
dev_dependencies:
  flutter_lints: ^6.0.0
  custom_lint: ^0.8.1
  df_safer_dart_lints: ^0.5.2

