name: example
publish_to: 'none'
environment:
  sdk: ^3.7.0
dependencies:
  flutter:
    sdk: flutter
  df_pod: ^0.16.10
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.4.0
  df_localization:
    path: ../
  df_config: ^0.7.1
  df_safer_dart: ^0.11.1
dev_dependencies:
  flutter_lints: ^5.0.0