name: df_localization_example
homepage: https://dev-cetera.com/
repository: https://github.com/robmllze/df_localization
funding:
- https://www.buymeacoffee.com/dev_cetera
- https://www.patreon.com/c/RobertMollentze
- https://github.com/sponsors/robmllze
publish_to: 'none'
environment:
  sdk: ">=3.5.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.4.0
  df_localization:
    path: ../
  df_config: ^0.7.5
  df_safer_dart: ^0.17.3
  df_pod: ^0.18.10
dev_dependencies:
  flutter_lints: ^6.0.0
  custom_lint: ^0.7.5
  df_safer_dart_lints: ^0.3.3

