##.title
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##
## Dart/Flutter (DF) Packages by dev-cetera.com & contributors. The use of this
## source code is governed by an MIT-style license described in the LICENSE
## file located in this project's root directory.
##
## See: https://opensource.org/license/mit
##
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##.title~

name: df_localization
description: A package that simplifies adding localization to your Flutter app.
version: 0.5.11
homepage: https://dev-cetera.com
repository: https://github.com/dev-cetera/df_localization
funding:
  - https://www.buymeacoffee.com/dev_cetera
topics:
  - configuration
  - locale
  - localization
  - state-management
  - translation

## -----------------------------------------------------------------------------

environment:
  sdk: ">=3.5.0 <4.0.0"

## -----------------------------------------------------------------------------

dependencies:
  flutter:
    sdk: flutter

  df_config: ^0.7.0
  df_log: ^0.2.4
  df_pod: ^0.16.6
  df_safer_dart: ^0.10.0
  http: ^1.3.0
  shared_preferences: ^2.5.2

  args: ^2.7.0
  path: ^1.9.0
  yaml: ^3.1.3

  google_generative_ai: ^0.4.6

## -----------------------------------------------------------------------------

dev_dependencies:
  flutter_lints: ^5.0.0

  ## -----------------------------------------------------------------------------

executables:
  gen-translations-gemeni: gen_translations_gemeni
